### PR TITLE
Keep `mysqldump`

### PR DESCRIPTION
**Pull request by Luc45**
This PR keeps `mysqldump` binary in the image. I'm curious to see how many `kbs` it adds to the image.

### CODE REVIEW

**Comment by Luc45** [comment]
Hmm, it seems this would add 3.6 mb to the image :thinking:

```
docker run --rm temp-mariadb sh -c "du -h /usr/bin/mariadb-dump"                                                                                                 
3.6M    /usr/bin/mariadb-dump
```

**Comment by Luc45** [comment]
Feel free to close this PR. 3.6 mb on a 15mb image is too much.

**Comment by jbergstroem** [comment]
> Would it make sense to release a "slim" version, that has a bit more stuff? For now, only mysqldump, but maybe some other nice-to-haves for specific cases.

This would imply automating a build process that publishes all permutations.

To me, this container covers more or less everything from a server standpoint, especially for a local development setup. I wonder if having a similar setup for client tools makes sense?

**Comment by Luc45** [comment]
Indeed.

For my personal use case, I've worked around this by having a `mariadb-dump` binary on the host that I add to the alpine image as a volume.

I think a "slim" version of the image can be put on hold until there's more demand to it, what do you think?

If anyone stumbles into this PR, the most appropriate place to discuss it seems to be: https://github.com/jbergstroem/mariadb-alpine/discussions/230

**Review by williamdes — APPROVED** [review]
It makes sense, but yeah same topic as for #212 where I need mysqladmin and not an alternative

**Comment by jbergstroem** [comment]
> It makes sense, but yeah same topic as for https://github.com/jbergstroem/mariadb-alpine/issues/212 where I need mysqladmin and not an alternative

Just wanted to chip in here. I still am not sure why you need mysqladmin since all it does is connect and does `select 1`; which I already accomplish in the PR! If its about not changing any existing scripts on your side I guess it makes sense? As you can see, sacrifices in convenience are made to achieve the smallest possible container.

**Comment by williamdes** [comment]
> > It makes sense, but yeah same topic as for #212 where I need `mysqladmin` and not an alternative
> 
> Just wanted to chip in here. I still am not sure why you need `mysqladmin` since all it does is connect and does `select 1`; which I already accomplish in the PR! If its about not changing any existing scripts on your side I guess it makes sense? As you can see, sacrifices in convenience are made to achieve the smallest possible container.

I think what you are trying is very nice and should be in a `-slim` variant. But users could expect to have the same tools at a default mariabdb package/image and not something else

**Comment by jbergstroem** [comment]
>  But users could expect to have the same tools at a default mariabdb package/image and not something else

Perhaps the project is not explaining its purpose clearly enough? Do you have suggestions to how we can improve it?

**Comment by williamdes** [comment]
> > But users could expect to have the same tools at a default mariabdb package/image and not something else
> 
> Perhaps the project is not explaining its purpose clearly enough? Do you have suggestions to how we can improve it?

I think you are right, maybe my expectations where the wrong ones
It's been years since my initial use of your project
Maybe at the time I just wanted to have alpine containers running
Not really sure, but the README is clear and makes sense

So maybe we can conclude that having a `-tools` variant would help

**Comment by jbergstroem** [comment]
> So maybe we can conclude that having a `-tools` variant would help

Makes sense to me! I'm expanding the list of utils here: https://github.com/jbergstroem/mariadb-alpine/discussions/230#discussioncomment-5553714 - lmk if I'm missingg something.

**Comment by jbergstroem** [comment]
Going to close this PR since I think we got a lot of useful info out of the discussion, but we won't be landing it in its current shape.

Sorry for the quiet, I will pick up a bit of slack in this area shortly.

**Pull request closed without merging**
