### PR TITLE
dockerfile: optimize cleanup

### PR DESCRIPTION
**Pull request by jbergstroem**
We previously called `tail` on output from `apk`. This is a remnant from an older script that handled output differently.

This means we now remove more files that shouldn't be part of the distribution.

### CODE REVIEW

**Review by williamdes — APPROVED** [review]

**Review by williamdes — COMMENTED** [review]
I am not sure why removing the comment is better

**Comment by jbergstroem** [comment]
> I am not sure why removing the comment is better

Just felt like we were stating the obvious. As a user they likely won't understand most of the work done in there and as a dev/mysql developer you likely have worked with the hosts table before. You think it serves a purpose?

Also, I am rewriting the test suite with `bash_unit` and will land that before doing continuous work – too many corner cases I wanna test properly.

**Review by williamdes — COMMENTED** [review]
I feel like the comment is important because it is not very obvious what you are trying to do
Maybe leave it
I did quite a bunch of setups and just looking at the link would make be doubt why it it there
The comment just explains that it is to change the allow any host to connect

**Comment by jbergstroem** [comment]
> Maybe leave it

Done

**Review by williamdes — APPROVED** [review]

**Review by williamdes — APPROVED** [review]

**Pull request merged**
